### ISSUE TITLE
does it work now?

### ISSUE THREAD

**Issue by xmaple555** [natsuminoneko/wy#2]
even the private server have updated few times so far, does it still work now? thank you in advance.

**Comment by danzoo** [comment]
yes

**Comment by bigphilly8** [comment]
@natsuminoneko @xmaple555 @danzoo how do you download this and get it working?  The zip only seems to have a text and image file without anything to run.

**Comment by danzoo** [comment]
> @natsuminoneko @xmaple555 @danzoo how do you download this and get it working? The zip only seems to have a text and image file without anything to run.

download release no original code

**Comment by danzoo** [comment]
> @natsuminoneko @xmaple555 @danzoo how do you download this and get it working? The zip only seems to have a text and image file without anything to run.

do not download source code but release file

**Comment by xmaple555** [comment]
thank you a lot. it works. but i got banned on mapleroyal. so now i need to reverse it for mac address. well, thank anyway
